name: mis_unas_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  smooth_page_indicator: ^2.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Añadimos el generador de iconos aquí
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  # IMPORTANTE: Descomentamos esto para que la app reconozca la carpeta assets
  assets:
    - assets/

# Configuración del nuevo logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21